apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "strapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "strapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: strapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: HOST
              value: {{ .Values.env.HOST | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: APP_KEYS
              value: {{ .Values.env.APP_KEYS | quote }}
            - name: API_TOKEN_SALT
              value: {{ .Values.env.API_TOKEN_SALT | quote }}
            - name: ADMIN_JWT_SECRET
              value: {{ .Values.env.ADMIN_JWT_SECRET | quote }}
            - name: TRANSFER_TOKEN_SALT
              value: {{ .Values.env.TRANSFER_TOKEN_SALT | quote }}
            - name: JWT_SECRET
              value: {{ .Values.env.JWT_SECRET | quote }}
            - name: DATABASE_CLIENT
              value: {{ .Values.database.type | quote }}
            - name: DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.database.name | quote }}
            - name: DATABASE_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: DATABASE_SSL
              value: {{ .Values.database.ssl | quote }}
          livenessProbe:
            httpGet:
              path: /_health
              port: 1337
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_health
              port: 1337
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: uploads
              mountPath: /app/public/uploads
            - name: data
              mountPath: /app/.tmp
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "strapi.fullname" . }}-uploads
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "strapi.fullname" . }}-data
      {{- end }}